package:
    name: dynamiq_engine-dev
    version: "0.0.1"

source:
    git_url: https://github.com/dynamiq-md/dynamiq_engine.git

requirements:
    build:
        - python
        - setuptools
        - numpy

    run:
        - python
        - numpy
        - scipy
        - pandas
        - openpathsampling-dev


test:
    requires:
        - nose
        - python-coveralls

    imports:
        - dynamiq_engine
