language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    # TODO: need to download and build dynamiq_engine in test environment
    - export PYTHONUNBUFFERED=true

script:
    - conda install --yes conda-build
    - conda build devtools/conda-recipe
    
    - source activate _test
    # this is where we install dynamiq_engine
    - ls
    - export PYWIGNER=`pwd`
    - cd && git clone https://github.com/dynamiq-md/dynamiq_engine
    - ls
    - cd dynamiq_engine && python setup.py install
    - cd $PYWIGNER
    - ls
    # end of dynamiq_engine install
    #- nosetests -v --with-coverage

after_success:
    #- coveralls

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
