package:
  name: pywigner-dev
  version: !!str 0.0.1

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - numpy
    - setuptools
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - jinja2
    - mdtraj
    - svgwrite
    - networkx
    - openpathsampling-dev

  run:
    - python
    - pandas
    - numpy
    - scipy
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - pyyaml
    - jinja2
    - mdtraj
    - svgwrite
    - networkx
    - openpathsampling-dev

about:
  home: https://github.com/dwhswenson/pyWigner
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
